name: hotel
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  equatable: ^2.0.5
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  masked_text: ^1.1.2
  mask_text_input_formatter: ^2.5.0
  email_validator: ^2.1.17
  numbers_to_words_russian: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/close.png
    - assets/images/emoji_happy.png
    - assets/images/tick_square.png
    - assets/images/party_popper.png
    

  fonts:
    - family: SF
      fonts:
        - asset: assets/SF_Pro_Display.otf